### ISSUE TITLE
Implement Backlog

### ISSUE THREAD

**Issue by mpiot** [Ludoutt/IUTgroupeB1#2]
Un utilisateur doit pouvoir ajouter, modifier, supprimer, lister, voir, ordonner, et changer le status d'un élément de Backlog.

- [x] Install Doctrine extension
- [x] Voter
- [x] Entity
- [x] Create fixtures
- [x] Create action
- [x] Edit action
- [x] Index action
- [x] Show action
- [x] Delete action
- [x] Ordering actions
- [x] Workflow
- [x] Smoking tests (PHPUnit)

Scheme:
 - [x] **id** INT NOT NULL AUTOINCREMENT
 - [x] **name** VARCHAR 255 NOT NULL
 - [x] **description** TEXT NULL
 - [x] **type**VARCHAR 255 NOT NULL
 - [x] **position** Doctrine Sortable Trait 
 - [x] **createdAt** Doctrine TimestampableTrait
 - [x] **updatedAt** Doctrine TimestampableTrait
 - [x] **createdBy** Doctrine BlameableTrait
 - [x] **updatedBy** Doctrine BlameableTrait

Acceptations:
 - [x] Type d'éléments: Épique, User story (attaché à des fonctionnalités), Fonctionnalité, Bug, Tâche technique
 - [x] Status workflow: Suggéré, accepté (PO), estimé (dev), planifier (PO), en cours (dev), en validation (dev), terminé (PO), abandonné (PO) (+ raison)

**Comment by mpiot** [comment]
ping @gregoire-petitalot @RomainoSoko @iMinosGFX @Bran72 : Entity Scheme proposal

**Comment by gregoire-petitalot** [comment]
How do I name my entity ? @mpiot
